          " _
 " __   __ (_)  _ __ ___    _ __    ___
 " \ \ / / | | | '_ ` _ \  | '__|  / __|
  " \ V /  | | | | | | | | | |    | (__
   " \_/   |_| |_| |_| |_| |_|     \___|

augroup automation
   autocmd!
augroup END

colorscheme one
let g:one_allow_italics = 1
