#!/usr/bin/env sh

# sh -c "sleep 0.5;  stalonetray -bg \"#000000\" --geometry \"1x1+125+5\"" &
# doas killall compton mpd polybar connman-vpnd picom
# pulseaudio --start &
# [ -f ~/.config/X11/Xresources ] && xrdb ~/.config/X11/Xresources &

# # Lunch Dbus
# if [ -d /etc/X11/xinit/xinitrc.d ] ; then
#  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#   [ -x "$f" ] && . "$f"
#  done
#  unset f
# fi

# Launches Transmission Daemon
# transmission-daemon &
# Launch Personal Scripts
mirror --mail &
ub-server &
watchmen --dots --mails &
bolt --generate &
alfred --background shuffle --dpi &
# Launch Compositor
sh -c "sleep 1 && $COMPOSITOR" &
# Set Locker
sh -c "xset s $INACTIVITY; xss-lock --ignore-sleep screensaver" &
# Speed key reapeat of pressing
xset r rate 200 30 &
# Launche notification server
dunst &
# Bind Multi-purpose keys
sh -c "xmodmap $LAYOUT_EN; xcape -e \"Super_L=Escape;Mode_switch=Tab\"" &
# Bind key commands
sxhkd &
# Bind gesture commands
gebaard -b &
# Remove X cursor
xsetroot -cursor_name left_ptr &
# Hide cursor while idle
unclutter &
# Launche bar
# sh -c "sleep 1 && $STATUS_BAR" &
$STATUSBAR &
# Luanche Window Manager
exec "$WM"
