#!/usr/bin/env sh

bspc rule -r    "*"                         # remove all previous rules
bspc rule -a    Zathura     state=tiled
bspc rule -a    guvcview    state=floating stikcy=on layer=above rectangle=480x270+1440+810
bspc rule -a    Screenkey manage=off

# bspc rule -a    Rofi    	follow=on
# bspc rule -a    XTerm    	follow=on state=fullscreen

#bspc rule -a    "*"         split_dir=east
#bspc query -N -n focused.automatic && echo "split_dir=south"

#----------[ Nodes & Desktops ]-----------------

bspc monitor -d                           	1 2 3 4 5
bspc desktop -f 	                        3
bspc desktop -l			                next

bspc config automatic_scheme 			spiral
bspc config initial_polarity			first_child

bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
bspc config merge_overlapping_monitors	true

#----------[ Nodes & Desktops ]-----------------

bspc config focus_follows_pointer	true

# bspc config pointer_follows_focus	true

bspc config split_ratio	            0.60

#bspc config history_aware_focus	true
#bspc config focus_by_distance		true

#----------[ Borders, Gaps & Paddings ]-----------------

bspc config border_width			2
bspc config window_gap 				50

bspc config top_padding 			35
# bspc config right_padding 			50
# bspc config bottom_padding 			50
# bspc config left_padding 			50

bspc config borderless_monocle		true
bspc config gapless_monocle			true
# bspc config single_monocle			true

#----------[ Colors ]-----------------

bspc config normal_border_color		"#FFFFFF"
bspc config focused_border_color	"#0000FF"

# bspc config urgent_border_color		"#B58900"
# bspc config presel_border_color		"#26E2FF"

# bspc rule -a urxvt state=fullscreen
# bspc rule -a Gimp desktop='^8' state=floating
# bspc rule -a subl3 desktop='^1'
# bspc rule -a xfce4-panel floating=on manage=off
# bspc rule -a xfce4-session floating=on fullscreen=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc rule -a Conky sticky=on manage=off lower=on

################################################################################
#                             Pointer
################################################################################

# bspc config pointer_modifier lock
# bspc config pointer_action1 move
# bspc config pointer_action2 resize_side
# bspc config pointer_action3 resize_corner
# bspc config click_to_focus none
